# Generated by Django 6.0.1 on 2026-02-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='dicount_price',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
